"use client";
import {useState,useEffect,useRef} from "react";
import Link from "next/link";
import {Activity,ArrowUpRight,ArrowLeft,Copy,Share2,Clock3,ShieldCheck,ArrowRight,Radio} from "lucide-react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Input} from "@/components/ui/input";
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from "@/components/ui/accordion";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {Pagination,PaginationContent,PaginationItem} from "@/components/ui/pagination";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {ASSETS,RESULTS,statusView,reasonLabel,safeReturn,signalWindow} from "@/lib/domain.mjs";
import {useApp,useRemote,useFilters,Title,UpdateButton,StateBox,Notice,Choice,assetOptions,directionOptions,resultOptions,dateTime,money,number,ResultPill,Direction,Coin,AgeLine,SignalCard,External} from "./shared";
export function Signals(){
 const app=useApp(),f=useFilters(),remote=useRemote("/api/public/signals?"+f.query,app.prefs.autoRefresh),stats=useRemote("/api/public/stats?"+new URLSearchParams([...new URLSearchParams(f.query)].filter(([k])=>k!=="cursor"&&k!=="result")),app.prefs.autoRefresh);
 const defaultApplied=useRef(false);
 useEffect(()=>{if(!app.prefsReady||defaultApplied.current)return;defaultApplied.current=true;if(!f.params.has("asset")&&app.prefs.asset!=="ALL")f.change({asset:app.prefs.asset});},[app.prefsReady]);
 const selected=f.params.get("asset")||"ALL";
 return <><Title eyebrow="BTC · ETH · SOL" title="Sinais do mercado" description="M15 + M5 → M1. Acompanhe a análise e a apuração." action={<UpdateButton remote={remote} onExtra={()=>{app.health.reload();stats.reload()}}/>}/>
 <div className="market-overview">{ASSETS.map(a=>{const item=app.health.data?.assets.find(x=>x.asset===a.code)?.record,v=statusView(item,app.now);return <Link key={a.code} href={"/status?asset="+a.code} className="market-tile"><div className="coin-name"><Coin asset={a.code}/><div><strong>{a.name}</strong><span>{a.pair}</span></div><ArrowUpRight className="tile-arrow" size={18}/></div><strong className="market-price">{money(item?.price)}</strong><div className="tile-caption"><span>Referência da análise</span><span className={v.kind}>{v.label}</span></div></Link>})}</div>
 <div className="metrics-strip"><div><span>Taxa de referência</span><strong>{stats.data?(stats.data.rate===null?"Sem amostra":number(stats.data.rate,1)+"%"):"Indisponível"}</strong></div><div><span>Amostra válida</span><strong>{stats.data?number(stats.data.sample,0):"—"} <small>WIN + LOSS</small></strong></div><div><span>Fonte de análise</span><strong className="metric-small">Coinbase / Kraken</strong></div><Link href={f.build({cursor:null,result:null},"/estatisticas")}>Ver estatísticas<ArrowUpRight size={18}/></Link></div>
 {!app.health.data?.assets.some(x=>x.record)&&<Notice><strong>Não conectado ao motor.</strong> Os sinais reais aparecerão após a sincronização. <Link href="/status">Ver status</Link></Notice>}
 <section className="section-block"><div className="section-heading"><div><p className="eyebrow">ACOMPANHAMENTO</p><h2>Sinais registrados</h2></div><Link className="text-link" href={f.build({cursor:null},"/historico")}>Ver histórico<ArrowRight size={16}/></Link></div>
 <Tabs value={selected} onValueChange={asset=>f.change({asset})}><div className="signal-filters"><TabsList aria-label="Filtrar por ativo" className="asset-tabs">{[["ALL","Todos"],["BTC","BTC"],["ETH","ETH"],["SOL","SOL"]].map(([v,l])=><TabsTrigger value={v} key={v}>{l}</TabsTrigger>)}</TabsList><Choice id="signal-direction" label="Direção" value={f.params.get("direction")} onChange={direction=>f.change({direction})} options={directionOptions}/></div><TabsContent value={selected}><StateBox remote={remote} empty={remote.data?.items.length===0}/>{remote.data?.items.length>0&&<div className="signals-grid">{remote.data.items.map(s=><SignalCard signal={s} origin={f.origin} key={s.id}/>)}</div>}</TabsContent></Tabs>
 <AgeLine serverNow={remote.data?.serverNow}/><p className="method-note"><ShieldCheck size={16}/>Score técnico não é probabilidade de acerto.<Link href="/ajuda">Entender o score</Link></p></section></>
}
export function HistoryView(){
 const app=useApp(),f=useFilters(),remote=useRemote("/api/public/signals?"+f.query,app.prefs.autoRefresh);
 const defaults=()=>Object.fromEntries(["asset","direction","result","from","to","version"].map(k=>[k,f.params.get(k)||""]));
 const [draft,setDraft]=useState(defaults),[formError,setFormError]=useState("");
 useEffect(()=>{setDraft(defaults());setFormError("")},[f.query]);
 const apply=e=>{e.preventDefault();if(draft.from&&draft.to&&draft.from>draft.to){setFormError("A data inicial deve ser anterior à data final.");return;}setFormError("");f.change(draft)};
 const set=(key,value)=>setDraft(x=>({...x,[key]:value==="ALL"?"":value}));
 return <><Title eyebrow="REGISTRO E APURAÇÃO" title="Histórico de sinais" description="Uma linha por sinal. A fonte e o horário originais são preservados." action={<UpdateButton remote={remote}/>}/>
 <form className="filter-panel" onSubmit={apply}><div className="filter-grid"><Choice id="history-asset" label="Ativo" value={draft.asset} onChange={v=>set("asset",v)} options={assetOptions}/><Choice id="history-direction" label="Direção" value={draft.direction} onChange={v=>set("direction",v)} options={directionOptions}/><Choice id="history-result" label="Resultado" value={draft.result} onChange={v=>set("result",v)} options={resultOptions}/><div className="field"><label htmlFor="date-from">De · Manaus</label><Input id="date-from" type="date" value={draft.from} onChange={e=>set("from",e.target.value)}/></div><div className="field"><label htmlFor="date-to">Até · Manaus</label><Input id="date-to" type="date" value={draft.to} onChange={e=>set("to",e.target.value)}/></div><div className="field"><label htmlFor="version">Versão da estratégia</label><Input id="version" value={draft.version} placeholder="Todas as versões" maxLength={40} onChange={e=>set("version",e.target.value)}/></div></div><div className="filter-actions"><Button type="submit">Aplicar filtros</Button><Button variant="ghost" type="button" onClick={()=>{setDraft({asset:"",direction:"",result:"",from:"",to:"",version:""});setFormError("");f.router.push("/historico")}}>Limpar</Button><Link className="text-link" href={f.build({cursor:null,result:null},"/estatisticas")}>Ver estatísticas deste período<ArrowUpRight size={16}/></Link></div>{formError&&<p role="alert" className="negative">{formError}</p>}</form>
 <StateBox remote={remote} empty={remote.data?.items.length===0}/>{remote.data?.items.length>0&&<section className="table-panel"><div className="table-panel-top"><h2>Registros</h2><span>{number(remote.data.total,0)} sinais encontrados</span></div><Table><TableHeader><TableRow><TableHead>Ativo / direção</TableHead><TableHead>Entrada · Manaus</TableHead><TableHead>Score</TableHead><TableHead>Fonte</TableHead><TableHead>Resultado</TableHead><TableHead><span className="sr-only">Detalhes</span></TableHead></TableRow></TableHeader><TableBody>{remote.data.items.map(s=><TableRow key={s.id} tabIndex={0} aria-label={"Abrir sinal "+s.id} onClick={e=>{if(!e.target.closest("a,button"))f.router.push("/sinal/"+s.id+"?returnTo="+encodeURIComponent(f.origin))}} onKeyDown={e=>{if(e.key==="Enter"&&e.target===e.currentTarget)f.router.push("/sinal/"+s.id+"?returnTo="+encodeURIComponent(f.origin))}}><TableCell><Link href={"/sinal/"+s.id+"?returnTo="+encodeURIComponent(f.origin)} className="table-asset"><Coin asset={s.asset}/><div><strong>{s.pair}</strong><Direction value={s.direction}/>{s.demo&&<small>TESTE</small>}</div></Link></TableCell><TableCell>{dateTime(s.entryAt)}</TableCell><TableCell>{number(s.score,0)}<small>/100</small></TableCell><TableCell>{s.source}</TableCell><TableCell><ResultPill value={s.result}/></TableCell><TableCell><Button asChild variant="ghost" size="icon"><Link href={"/sinal/"+s.id+"?returnTo="+encodeURIComponent(f.origin)} aria-label={"Ver sinal "+s.id}><ArrowUpRight size={18}/></Link></Button></TableCell></TableRow>)}</TableBody></Table><Pagination className="pagination"><PaginationContent><PaginationItem><Button variant="outline" disabled={!f.params.get("cursor")} onClick={()=>f.router.push(f.build({cursor:null}))}>Primeira página</Button></PaginationItem><PaginationItem><Button variant="outline" disabled={!remote.data.nextCursor} onClick={()=>f.router.push(f.build({cursor:remote.data.nextCursor}))}>Próxima página<ArrowRight size={16}/></Button></PaginationItem></PaginationContent></Pagination></section>}<AgeLine serverNow={remote.data?.serverNow}/></>
}
export function StatsView(){
 const app=useApp(),f=useFilters(),clean=new URLSearchParams(f.query);clean.delete("cursor");clean.delete("result");
 const remote=useRemote("/api/public/stats?"+clean,app.prefs.autoRefresh),d=remote.data;
 return <><Title eyebrow="TRANSPARÊNCIA" title="Estatísticas" description="Amostra completa do período selecionado, sem estimativa de lucro." action={<UpdateButton remote={remote}/>}/><div className="scope-panel"><p><strong>Escopo:</strong> {f.params.get("asset")||"Todos os ativos"} · {f.params.get("direction")||"Todas as direções"} · {f.params.get("from")||"Início do histórico"} a {f.params.get("to")||"hoje"} · {f.params.get("version")||"Todas as versões"}</p><Link href={f.build({cursor:null,result:null},"/historico")} className="text-link">Ajustar período e filtros<ArrowUpRight size={15}/></Link></div>
 <StateBox remote={remote}/>{d&&<><div className="stats-highlight"><section className="rate-card"><p className="eyebrow">TAXA DE REFERÊNCIA</p><strong className="big-rate">{d.rate===null?"Sem amostra":number(d.rate,1)+"%"}</strong><p>WIN ÷ (WIN + LOSS) × 100</p><div className={"rate-track "+(d.rate===null?"no-sample":"")} role="img" aria-label={d.rate===null?"Sem amostra":number(d.rate,1)+" por cento de WIN"}><span style={{width:(d.rate||0)+"%"}}/></div><div className="rate-key"><span className="positive">{number(d.wins,0)} WIN válidos</span><span className="negative">{number(d.losses,0)} LOSS válidos</span></div></section><section className="sample-card"><Activity size={26}/><p>Amostra válida</p><strong>{number(d.sample,0)}</strong><span>Registros reais, confirmados e apurados</span><dl><div><dt>Total no escopo</dt><dd>{number(d.total,0)}</dd></div><div><dt>Fora do denominador</dt><dd>{number(d.excluded,0)}</dd></div></dl></section></div>
 <section className="section-block"><div className="section-heading"><h2>Resultados no escopo</h2><Link href={f.build({cursor:null,result:null},"/historico")} className="text-link">Ver todos<ArrowRight size={16}/></Link></div><div className="result-grid">{RESULTS.map(r=><Link key={r} href={f.build({cursor:null,result:r},"/historico")} className={"result-count result-"+r.toLowerCase()}><ResultPill value={r}/><strong>{number(d.counts[r],0)}</strong><span>Ver registros<ArrowUpRight size={15}/></span></Link>)}</div></section>
 <section className="info-panel"><h2>Como ler esta amostra</h2><p>EMPATE, INCONCLUSIVO, PENDENTE, cancelados, dados de teste e publicações não confirmadas ficam fora de WIN + LOSS. A entrega incerta da mensagem de resultado não invalida uma apuração confirmada.</p><p>{d.cancelled} cancelados · {d.uncertain} sem publicação confirmada · {d.demo} de teste.</p><p>Versões: {d.versions.length?d.versions.join(", "):"Sem registros"}</p><Link className="text-link" href="/ajuda">Como calcular<ArrowUpRight size={16}/></Link></section></>}<AgeLine serverNow={d?.serverNow}/></>
}
export function DetailView({id}){
 const app=useApp(),f=useFilters(),remote=useRemote("/api/public/signals/"+encodeURIComponent(id),app.prefs.autoRefresh),s=remote.data?.signal,back=safeReturn(f.params.get("returnTo")),resultRef=useRef(null);
 const [copyFallback,setCopyFallback]=useState(null);
 useEffect(()=>{if(s&&f.params.get("view")==="result")resultRef.current?.scrollIntoView({behavior:"smooth",block:"start"})},[s?.id,f.params.get("view")]);
 const copy=async value=>{try{if(!navigator.clipboard)throw 0;await navigator.clipboard.writeText(value);toast.success("Copiado.")}catch{setCopyFallback(value)}};
 const share=async()=>{const url=app.config?.canonicalOrigin+"/sinal/"+encodeURIComponent(s.id);if(navigator.share){try{await navigator.share({title:"VINSETT · "+s.pair,url});return}catch(e){if(e.name==="AbortError")return;}}await copy(url)};
 const win=s&&signalWindow(s,{now:app.now,uncertainty:app.online?app.uncertainty:Infinity,enabled:app.config?.windowEnabled===true});
 return <><Link href={back} className="back-link"><ArrowLeft size={16}/>Voltar</Link><Title eyebrow="REGISTRO ORIGINAL" title={s?s.pair+" · "+(s.direction==="BUY"?"Compra":"Venda"):"Detalhes do sinal"} action={<UpdateButton remote={remote}/>}/>{remote.error?.includes("Sinal não encontrado")?<section className="info-panel"><h2>Sinal não encontrado</h2><p>O ID informado não corresponde a um registro público.</p><Button asChild><Link href="/historico">Abrir histórico</Link></Button></section>:<StateBox remote={remote}/>}
 {s&&<><div className="detail-top"><div className="detail-summary"><div className="section-heading"><Direction value={s.direction}/><ResultPill value={s.result}/></div><p className="detail-score">{number(s.score,0)}<span>/100</span></p><p>Score técnico · <Link href="/ajuda">Entender o score</Link></p><div className={"window-state "+win.kind}><Clock3 size={16}/>{win.label}</div><p className="mono signal-id">{s.id}</p><div className="button-row"><Button variant="outline" onClick={()=>copy(s.id)}><Copy size={15}/>Copiar ID</Button>{app.config?.canonicalOrigin?<Button variant="outline" onClick={share}><Share2 size={15}/>Compartilhar</Button>:<span className="muted text-sm">Compartilhamento disponível após publicação.</span>}</div></div><div className="detail-metadata"><h2>Horários e origem</h2><dl>{[["Fonte",s.source+" · "+s.symbol],["Análise",dateTime(s.analyzedAt)],["Publicado no Telegram",dateTime(s.publishedAt)],["Entrada anunciada",dateTime(s.entryAt)],["Fim M1",dateTime(s.endAt)],["Sincronizado com o app",dateTime(s.syncedAt)],["Preço de referência",money(s.referencePrice)],["Estratégia / revisão",s.strategyVersion+" / "+s.revision]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="muted text-sm">Todos os horários em America/Manaus. Atualizar a tela não altera a entrada.</p></div></div>
 <div className="notice muted"><ShieldCheck size={18}/><span>{reasonLabel[s.reason]||"Diagnóstico indisponível"}. A cotação de referência não representa execução em corretora.</span></div>
 <section className="info-panel"><Accordion type="single" collapsible><AccordionItem value="indicators"><AccordionTrigger>Indicadores da análise</AccordionTrigger><AccordionContent><Table><TableHeader><TableRow><TableHead>Indicador</TableHead><TableHead>M15</TableHead><TableHead>M5</TableHead><TableHead>M1</TableHead></TableRow></TableHeader><TableBody>{[["EMA 9","emaFast"],["EMA 21","emaSlow"],["RSI 14","rsi"],["ATR 14 (%)","atrPct"],["Volume","volume"],["Média de volume 20","volumeMean"],["Fechamento","close"]].map(([label,key])=><TableRow key={key}><TableCell>{label}</TableCell>{["m15","m5","m1"].map(tf=><TableCell key={tf}>{number(s.indicators[tf]?.[key],6)}</TableCell>)}</TableRow>)}</TableBody></Table><p>RSI e ATR usam médias simples; EMA começa pela SMA. Valores ausentes permanecem indisponíveis.</p></AccordionContent></AccordionItem></Accordion></section>
 <div className="button-row"><Button asChild variant="outline"><Link href={"/sinal/"+s.id+"?view=result&returnTo="+encodeURIComponent(back)}>Ver resultado<ArrowRight size={16}/></Link></Button>{s.telegramUrl?<External href={s.telegramUrl}>Mensagem original no Telegram</External>:<p className="muted text-sm">Link público da mensagem não configurado.</p>}</div>
 <section className="info-panel" ref={resultRef}><div className="section-heading"><h2>Apuração deste sinal</h2><ResultPill value={s.result}/></div><p>Vela M1 do intervalo anunciado, no mesmo ativo e na fonte {s.source}.</p><div className="ohlc-grid">{[["Abertura","open"],["Máxima","high"],["Mínima","low"],["Fechamento","close"]].map(([label,key])=><div key={key}><span>{label}</span><strong>{money(s.candle?.[key])}</strong></div>)}</div><p>Apurado: {dateTime(s.assessedAt)} · Mensagem do resultado: {s.resultDelivery==="CONFIRMED"?"entrega confirmada":s.resultDelivery==="UNCERTAIN"?"entrega incerta":"pendente"}</p><Link href="/ajuda" className="text-link">Como é apurado<ArrowUpRight size={16}/></Link></section></>}
 <Dialog open={copyFallback!==null} onOpenChange={open=>{if(!open)setCopyFallback(null)}}><DialogContent><DialogHeader><DialogTitle>Copie manualmente</DialogTitle><DialogDescription>O navegador não permitiu a cópia automática. Selecione o texto abaixo.</DialogDescription></DialogHeader><Input aria-label="Texto para copiar" readOnly value={copyFallback||""} onFocus={e=>e.target.select()}/><Button onClick={()=>setCopyFallback(null)}>Fechar</Button></DialogContent></Dialog><AgeLine serverNow={remote.data?.serverNow}/></>
}
