"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,ArrowUpRight,ArrowRight,Radio,ShieldCheck,LockKeyhole,Pause,Play,LogOut,Download,RotateCcw,Monitor,Sun,Moon,Check} from "lucide-react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {Switch} from "@/components/ui/switch";
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from "@/components/ui/accordion";
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import {ASSETS,statusView,reasonLabel} from "@/lib/domain.mjs";
import {useApp,useFilters,useRemote,Title,UpdateButton,StateBox,Notice,Choice,assetOptions,Coin,dateTime,number,External,AgeLine} from "./shared";
export function StatusView(){
 const app=useApp(),f=useFilters(),remote=app.health,[expanded,setExpanded]=useState(f.params.get("asset")||"");
 useEffect(()=>setExpanded(f.params.get("asset")||""),[f.params.get("asset")]);
 return <><Title eyebrow="FONTE E ATUALIDADE" title="Status do motor" description="A disponibilidade desta página não confirma que o motor está em execução." action={<UpdateButton remote={remote}/>}/><StateBox remote={remote}/><Accordion type="single" collapsible value={expanded} onValueChange={setExpanded} className="status-accordion">{ASSETS.map(a=>{const s=remote.data?.assets.find(x=>x.asset===a.code)?.record,v=statusView(s,app.now);return <AccordionItem value={a.code} key={a.code} className="status-panel"><AccordionTrigger><div className="status-panel-title"><Coin asset={a.code}/><div><strong>{a.pair}</strong><small>{a.name}</small></div><span className={"pill "+v.kind}>{v.label}</span></div></AccordionTrigger><AccordionContent><dl className="status-data">{[["Último ciclo",dateTime(s?.lastCycleAt)],["Última análise",dateTime(s?.analyzedAt)],["Última sincronização",dateTime(s?.syncedAt)],["Fonte",s?.source||"Indisponível"],["Diagnóstico",s?reasonLabel[s.reason]:"Não conectado"],["Idade M1 / M5 / M15",s?[s.ages.m1,s.ages.m5,s.ages.m15].map(n=>typeof n==="number"?number(n,0)+" s":"Indisponível").join(" / "):"Indisponível"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="muted text-sm">As idades correspondem à última análise informada pelo motor. Limites: M1 120 s; M5 420 s; M15 1.020 s.</p><div className="button-row"><Button asChild variant="outline"><Link href={"/?asset="+a.code}>Ver sinais de {a.code}<ArrowRight size={15}/></Link></Button><Link href="/ajuda" className="text-link">Entender problema<ArrowUpRight size={15}/></Link></div></AccordionContent></AccordionItem>})}</Accordion><Notice><strong>Acompanhamento, sem garantia de pontualidade.</strong> Apps Script, rede e Telegram podem atrasar. O horário anunciado permanece o mesmo.</Notice><AgeLine serverNow={remote.data?.serverNow}/></>
}
export function Preferences(){
 const app=useApp(),[install,setInstall]=useState(null);
 useEffect(()=>{if(!app.config?.pwaEnabled||!window.isSecureContext)return;
 navigator.serviceWorker?.register("/sw.js").catch(()=>{});
 const listen=e=>{e.preventDefault();setInstall(e)};window.addEventListener("beforeinstallprompt",listen);return()=>window.removeEventListener("beforeinstallprompt",listen)},[app.config?.pwaEnabled]);
 const change=(k,v)=>app.setPrefs({...app.prefs,[k]:v});
 return <><Title eyebrow="NESTE DISPOSITIVO" title="Preferências" description="Estas escolhas mudam apenas a visualização do app."/><section className="settings-panel"><div className="setting-row"><div><h2>Aparência</h2><p>Escolha o contraste de sua preferência.</p></div><Choice id="theme" label="Tema" value={app.prefs.theme} onChange={v=>change("theme",v)} options={[["dark","Escuro"],["light","Claro"]]}/></div><div className="setting-row"><div><h2>Ativo inicial</h2><p>Filtro usado ao abrir o painel sem um ativo na URL.</p></div><Choice id="preferred-asset" label="Ativo" value={app.prefs.asset} onChange={v=>change("asset",v)} options={assetOptions}/></div><div className="setting-row"><div><h2>Atualização automática</h2><p id="auto-hint">Consulta novos dados a cada 15 segundos enquanto a tela estiver visível.</p></div><Switch aria-label="Atualização automática" aria-describedby="auto-hint" checked={app.prefs.autoRefresh} onCheckedChange={v=>change("autoRefresh",v)}/></div><div className="setting-row"><div><h2>Instalar no celular</h2><p>{install?"Seu navegador disponibilizou a instalação.":"A instalação será disponibilizada após publicação e validação em um navegador compatível."}</p></div>{install&&<Button variant="outline" onClick={async()=>{await install.prompt();const choice=await install.userChoice;if(choice.outcome==="accepted")toast.success("Instalação solicitada ao navegador.");setInstall(null)}}><Download size={16}/>Instalar app</Button>}</div><div className="setting-row"><div><h2>Restaurar preferências</h2><p>Voltar ao tema escuro, todos os ativos e atualização automática.</p></div><AlertDialog><AlertDialogTrigger asChild><Button variant="outline"><RotateCcw size={16}/>Restaurar</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Restaurar preferências?</AlertDialogTitle><AlertDialogDescription>Somente as três preferências deste app neste dispositivo serão restauradas.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={()=>{app.restore();toast.success("Preferências restauradas.")}}>Restaurar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></section></>
}
const questions=[
 ["O que significa o score técnico?","É a pontuação das condições técnicas da estratégia, de 0 a 100. Não é probabilidade de acerto e não garante resultado. O motor V5 exige score de pelo menos 78, superior ao da direção oposta, além dos filtros obrigatórios."],
 ["Como as análises são realizadas?","O motor combina M15, M5 e M1. Usa EMA 9/21, RSI 14, ATR 14 e média de volume de 20 velas. A EMA começa pela SMA; RSI e ATR usam médias simples. A mesma fonte fornece o conjunto dos três períodos. A interface não calcula novos sinais por visitante."],
 ["Como WIN, LOSS e EMPATE são apurados?","É usada a vela M1 fechada do intervalo e da fonte anunciados. Em BUY, fechamento acima da abertura é WIN; abaixo, LOSS. Em SELL, a comparação se inverte. Preços iguais dão EMPATE. É um resultado de referência, sem confirmação de execução ou pagamento em corretora."],
 ["Quando o resultado fica PENDENTE ou INCONCLUSIVO?","A apuração começa após o fim da vela mais 5 segundos, na próxima execução do motor. Sem vela válida, o registro fica pendente. Após 30 minutos sem os dados exigidos, ou se a publicação ocorrer após a entrada, o resultado é inconclusivo. O app recebe as revisões do motor, sem trocar a fonte."],
 ["Por que posso ver Janela encerrada ou Antecedência insuficiente?","A entrada é um horário fixo. Atualizar a página não reinicia a contagem. Após a entrada, a janela está encerrada. Com menos de 8 segundos úteis ou horário incerto, não há janela validada. O app começa em acompanhamento; uma indicação de janela disponível exige validação da latência completa."],
 ["Como a taxa de referência é calculada?","WIN ÷ (WIN + LOSS) × 100, sobre todo o conjunto filtrado. Só entram sinais reais com publicação confirmada e apuração válida. Empates, pendentes, inconclusivos, cancelados, testes e publicações incertas ficam fora do denominador. Sem WIN ou LOSS válidos, aparece Sem amostra."],
 ["Entrega incerta é a mesma coisa que resultado inválido?","Não. Uma resposta de envio pode se perder. A entrega do sinal exige reconciliação e não deve ser reenviada às cegas. Quando a apuração já é válida, a entrega incerta da mensagem de resultado não invalida o WIN, LOSS ou EMPATE."],
 ["O que acontece ao pausar?","A pausa interrompe apenas novos sinais. Apurações pendentes continuam no motor preparado e fora de manutenção. O pedido do administrador fica solicitado até a confirmação do conector. Retomar exige que as condições de prontidão e saúde sejam atendidas."],
 ["Posso usar o app sem internet?","Os sinais e o status precisam de conexão. Uma instalação como PWA não transforma o motor em um serviço offline. Se não houver rede, o app não confirma atualidade, horários ou novas apurações."],
 ["O app opera na corretora ou trabalha com OTC?","Não executa ordens, não movimenta dinheiro e não conecta contas de corretoras. O escopo é BTC/USD, ETH/USD e SOL/USD das fontes Coinbase e Kraken. Não oferece OTC ou martingale."]
];
export function HelpView(){const app=useApp();return <><Title eyebrow="METODOLOGIA" title="Entenda os sinais" description="O que cada informação representa e como acompanhar os registros."/><section className="info-panel"><Accordion type="single" collapsible>{questions.map(([q,a],i)=><AccordionItem value={"faq-"+i} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent><p>{a}</p></AccordionContent></AccordionItem>)}</Accordion></section><section className="info-panel"><h2>Suporte e Telegram</h2>{app.config?.support?<External href={app.config.support}>Falar com o suporte</External>:<p>O contato público de suporte ainda não foi configurado.</p>}{app.config?.telegram?<External href={app.config.telegram}>Abrir Telegram</External>:<p>O link público do Telegram ainda não foi configurado.</p>}</section><Button variant="outline" asChild><Link href="/"><ArrowLeft size={16}/>Voltar aos sinais</Link></Button></>}
export function About(){return <><Title eyebrow="VINSETT SINAIS" title="Clareza em cada registro" description="Um painel público para acompanhar o VINSETT TRADER PRO V5."/><section className="info-panel prose-panel"><h2>Do motor ao histórico</h2><p>O VINSETT Sinais apresenta análises de referência de Bitcoin, Ethereum e Solana em USD. Cada sinal mantém um ID estável, direção, fonte e horários anunciados. As atualizações registram sua apuração e o estado de entrega.</p><h2>Fontes e método</h2><p>O motor usa Coinbase como fonte principal e Kraken como alternativa. Cada análise combina os três períodos da mesma fonte. A apuração permanece na fonte anunciada.</p><p>A consulta pública é somente leitura. A administração é restrita a contas autorizadas no servidor.</p><Button asChild variant="outline"><Link href="/ajuda">Ver metodologia<ArrowUpRight size={16}/></Link></Button></section></>}
export function Legal({kind}){const privacy=kind==="privacy";return <><Title title={privacy?"Privacidade":"Termos de uso"} eyebrow="VINSETT SINAIS"/><section className="info-panel prose-panel">{privacy?<><h2>Consulta pública</h2><p>O painel pode ser consultado sem cadastro. São apresentados apenas os campos públicos necessários para acompanhar os sinais, sua fonte e sua apuração.</p><h2>Preferências locais</h2><p>Tema, ativo inicial e atualização automática ficam no armazenamento do navegador deste dispositivo. O estado de navegação lateral pode usar um cookie local. A restauração de preferências limpa somente as três escolhas do app.</p><h2>Dados privados e administração</h2><p>Tokens, senhas, destinos privados do Telegram e filas operacionais não são entregues pela API pública. A planilha original permanece privada. A autenticação administrativa é realizada pelo provedor configurado; o servidor verifica a lista de contas autorizadas.</p><h2>Infraestrutura e contato</h2><p>A infraestrutura e o provedor de identidade podem processar informações técnicas de acesso para operar o serviço. O responsável pelo projeto deve configurar seu contato de suporte e as informações de retenção aplicáveis antes da publicação.</p><Link href="/ajuda" className="text-link">Consultar suporte</Link></>:<><h2>Finalidade</h2><p>Este app permite acompanhar análises e resultados de referência. Não executa ordens, não movimenta dinheiro e não acessa contas de corretoras.</p><h2>Limites das informações</h2><p>O score técnico não representa probabilidade de acerto. Não há garantia de lucro, taxa de acerto, disponibilidade ou pontualidade. Cotações e resultados de uma corretora podem diferir da vela usada na apuração.</p><h2>Horários e apuração</h2><p>O horário de entrada é fixo; atualizar ou abrir a página posteriormente não altera a janela anunciada. O histórico distingue pendências, publicações incertas, cancelamentos e resultados inconclusivos.</p><h2>Uso do painel</h2><p>Os dados públicos são somente leitura. Não é permitido tentar alterar resultados ou obter acesso administrativo sem autorização. O histórico não deve ser apresentado como comprovante de execução ou pagamento.</p></>}</section><Button asChild variant="outline"><Link href="/"><ArrowLeft size={16}/>Voltar ao início</Link></Button></>}
const commandLabels={REQUESTED:"Solicitado",CONFIRMED:"Confirmado pelo motor",REJECTED:"Rejeitado pelo motor",UNCERTAIN:"Execução incerta — reconciliar"};
export function AdminView({auth}){
 const remote=useRemote("/api/admin/state",true),app=useApp(),[action,setAction]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const confirm=async()=>{if(!action||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/admin/commands",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",cache:"no-store",body:JSON.stringify(action)}),d=await r.json();if(!r.ok)throw new Error(d.error?.message||"Não foi possível enviar o pedido.");toast.success("Pedido solicitado. Aguardando confirmação do motor.");setAction(null);remote.reload()}catch(e){setError(e.message+" O mesmo pedido será consultado em uma nova tentativa.")}finally{setBusy(false)}};
 return <><Title title="Administração" eyebrow="ACESSO RESTRITO" description={"Conectado como "+auth.displayName} action={<Button asChild variant="outline"><a href={auth.signOut} target="_top" onClick={()=>{sessionStorage.removeItem("vinsett.admin.cache")}}><LogOut size={16}/>Sair</a></Button>}/><StateBox remote={remote}/>{!app.config?.commandsEnabled?<Notice>O controle do motor está desconectado. Pausa e retomada serão disponibilizadas após a configuração e validação do conector.</Notice>:<section className="info-panel"><h2>Controle de novos sinais</h2><p>As apurações pendentes continuam durante a pausa. A confirmação depende do motor.</p><div className="button-row"><Button variant="outline" onClick={()=>setAction({kind:"PAUSE",idempotencyKey:crypto.randomUUID()})}><Pause size={16}/>Pausar novos sinais</Button><Button onClick={()=>setAction({kind:"RESUME",idempotencyKey:crypto.randomUUID()})}><Play size={16}/>Retomar</Button></div></section>}
 <section className="info-panel"><h2>Pedidos recentes</h2>{remote.data?.commands.length?remote.data.commands.map(c=><div className="command-row" key={c.id}><div><strong>{c.kind==="PAUSE"?"Pausar":"Retomar"}</strong><p>{dateTime(new Date(c.requestedAt).toISOString())}</p></div><span>{commandLabels[c.status]||c.status}</span></div>):<p className="muted">Nenhum pedido disponível.</p>}</section>
 <AlertDialog open={action!==null} onOpenChange={open=>{if(!open&&!busy){setAction(null);setError("")}}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{action?.kind==="PAUSE"?"Solicitar pausa?":"Solicitar retomada?"}</AlertDialogTitle><AlertDialogDescription>{action?.kind==="PAUSE"?"A pausa afeta somente novos sinais. Os resultados pendentes continuam sendo apurados.":"A retomada só será confirmada se o motor estiver preparado, fora de manutenção e sem falha de saúde."}</AlertDialogDescription></AlertDialogHeader>{error&&<p role="alert" className="negative">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><Button onClick={confirm} disabled={busy}>{busy?"Enviando…":error?"Consultar o mesmo pedido":"Confirmar pedido"}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></>
}
export function LoginView({auth,mode="login"}){
 const app=useApp(),enabled=auth?.enabled;
 return <><Title title={mode==="login"?"Acesso administrativo":mode==="recover"?"Recuperar acesso":"Redefinir acesso"} eyebrow="ÁREA RESTRITA"/><section className="auth-panel"><div className="auth-icon"><LockKeyhole size={30}/></div><h2>{mode==="login"?"Entre com sua conta autorizada":"Recuperação pelo provedor"}</h2><p>{mode==="login"?"Somente as contas incluídas na lista administrativa podem controlar o motor.":"A recuperação e a redefinição de senha são realizadas pelo provedor de identidade. O app não recebe sua senha nem valida tokens de recuperação locais."}</p>{enabled?<Button asChild className="auth-button"><a href={auth.signIn} target="_top">Continuar com ChatGPT<ArrowUpRight size={16}/></a></Button>:<Notice>Autenticação administrativa não configurada. A consulta pública continua disponível.</Notice>}{mode==="login"&&<Link href="/admin/recuperar" className="text-link">Esqueci meu acesso</Link>}{mode!=="login"&&<Link href="/admin/login" className="text-link">Voltar ao login<ArrowLeft size={16}/></Link>}{auth?.identity&&<div className="identity-box"><p>Conta identificada: {auth.identity.email}</p><p>Esta conta precisa ser autorizada pelo responsável do app.</p><code>{auth.identity.id}</code></div>}</section></>
}
export function NotFoundView({denied=false}){return <><Title title={denied?"Acesso negado":"Página não encontrada"} eyebrow={denied?"ACESSO RESTRITO":"ERRO 404"}/><section className="info-panel"><p>{denied?"Sua conta não está autorizada para esta área.":"O endereço informado não corresponde a uma página do VINSETT Sinais."}</p><div className="button-row"><Button asChild><Link href="/">Ir ao início</Link></Button><Button asChild variant="outline"><Link href={denied?"/admin/login":"/ajuda"}>{denied?"Abrir login":"Abrir ajuda"}</Link></Button></div></section></>}
